"""Bot Bootstrapper

Goal: make the Bots UI never feel "empty" on a fresh start.

The classic issue:
  - Swing bots only write their state files *after* they run.
  - The UI reads /api/eod/status which (by default) scans for those files.
  - On a brand new install or after cleanup, that scan returns 0 bots and the UI looks broken.

What we do here:
  - Ensure UI overlay defaults exist (enabled/aggression) for each known swing bot.
  - Ensure a minimal state file exists for each swing bot config (if missing).

This does NOT start trading, place orders, or force a cycle to run.
It just pre-creates deterministic, harmless local artifacts.
"""

from __future__ import annotations

import gzip
import json
from datetime import datetime
from pathlib import Path
from typing import Any, Dict

from backend.core.config import PATHS, TIMEZONE


def _root() -> Path:
    return Path(PATHS.get("root") or Path("."))


def _ml_data() -> Path:
    p = Path(PATHS.get("ml_data") or (_root() / "ml_data"))
    p.mkdir(parents=True, exist_ok=True)
    return p


def _stock_cache() -> Path:
    p = Path(PATHS.get("stock_cache") or (_root() / "data_cache"))
    p.mkdir(parents=True, exist_ok=True)
    return p


def _bot_state_dir() -> Path:
    d = _stock_cache() / "master" / "bot"
    d.mkdir(parents=True, exist_ok=True)
    return d


def _ui_overlay_path() -> Path:
    d = _ml_data() / "config"
    d.mkdir(parents=True, exist_ok=True)
    return d / "bots_ui_overrides.json"


def _read_json(path: Path) -> Dict[str, Any]:
    try:
        if path.exists():
            obj = json.loads(path.read_text(encoding="utf-8"))
            return obj if isinstance(obj, dict) else {}
    except Exception:
        pass
    return {}


def _write_json_atomic(path: Path, payload: Dict[str, Any]) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    tmp = path.with_suffix(path.suffix + ".tmp")
    tmp.write_text(json.dumps(payload, indent=2), encoding="utf-8")
    tmp.replace(path)


def ensure_swing_ui_defaults() -> None:
    """Ensure overlay defaults exist for each swing bot config."""
    try:
        from backend.bots import config_store  # type: ignore

        configs = config_store.load_all_bot_configs()
    except Exception:
        return

    overlay_path = _ui_overlay_path()
    overlay = _read_json(overlay_path)

    changed = False
    for bot_key in configs.keys():
        node = overlay.get(bot_key)
        if not isinstance(node, dict):
            overlay[bot_key] = {"enabled": True, "aggression": 0.5}
            changed = True
            continue
        if "enabled" not in node:
            node["enabled"] = True
            changed = True
        if "aggression" not in node:
            node["aggression"] = 0.5
            changed = True
        overlay[bot_key] = node

    if changed:
        overlay["_meta"] = {
            "updated_at": datetime.now(TIMEZONE).isoformat(),
            "note": "Autogenerated defaults for bots UI.",
        }
        _write_json_atomic(overlay_path, overlay)


def ensure_swing_state_files() -> None:
    """Create minimal swing bot state files if they don't exist yet."""
    try:
        from backend.bots import config_store  # type: ignore

        configs = config_store.load_all_bot_configs()
    except Exception:
        return

    state_dir = _bot_state_dir()

    for bot_key, cfg in configs.items():
        state_path = state_dir / f"rolling_{bot_key}.json.gz"
        if state_path.exists():
            continue

        initial_cash = float(getattr(cfg, "initial_cash", 0.0) or 0.0)
        payload = {
            "cash": initial_cash,
            "last_equity": initial_cash,
            "last_updated": datetime.now(TIMEZONE).isoformat(),
            "positions": {},
        }
        try:
            with gzip.open(state_path, "wt", encoding="utf-8") as f:
                json.dump(payload, f)
        except Exception:
            # If this fails, we just won't have a bootstrap state; UI still works via fallback.
            continue


def bootstrap_bots_for_ui() -> None:
    """Convenience: run all safe bootstrap steps."""
    ensure_swing_ui_defaults()
    ensure_swing_state_files()
